# -*- coding: utf-8 -*-
"""mi_primera_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14uS8HhY1nJykgarqC4gDQ9hIQpbGqoIT
"""

import streamlit as st

# Título de la app
st.title('Conversor Universal')

# Autor de la app
st.write('Esta app fue elaborada por Juan Camilo Torres Arboleda.')

# Selección de categoría
categoria = st.selectbox('Selecciona la categoría de conversión:',
                         ['Temperatura', 'Longitud', 'Peso/Masa', 'Volumen', 'Tiempo',
                          'Velocidad', 'Área', 'Energía', 'Presión', 'Tamaño de Datos'])

# Función para cada conversión
def convertir(categoria):
    if categoria == 'Temperatura':
        conversion = st.selectbox('Selecciona la conversión:',
                                  ['Celsius a Fahrenheit', 'Fahrenheit a Celsius',
                                   'Celsius a Kelvin', 'Kelvin a Celsius'])
        valor = st.number_input('Introduce el valor:')
        if conversion == 'Celsius a Fahrenheit':
            resultado = (valor * 9/5) + 32
        elif conversion == 'Fahrenheit a Celsius':
            resultado = (valor - 32) * 5/9
        elif conversion == 'Celsius a Kelvin':
            resultado = valor + 273.15
        elif conversion == 'Kelvin a Celsius':
            resultado = valor - 273.15
        st.write(f'El resultado es: {resultado}')

    elif categoria == 'Longitud':
        conversion = st.selectbox('Selecciona la conversión:',
                                  ['Pies a metros', 'Metros a pies',
                                   'Pulgadas a centímetros', 'Centímetros a pulgadas'])
        valor = st.number_input('Introduce el valor:')
        if conversion == 'Pies a metros':
            resultado = valor * 0.3048
        elif conversion == 'Metros a pies':
            resultado = valor / 0.3048
        elif conversion == 'Pulgadas a centímetros':
            resultado = valor * 2.54
        elif conversion == 'Centímetros a pulgadas':
            resultado = valor / 2.54
        st.write(f'El resultado es: {resultado}')

    elif categoria == 'Peso/Masa':
        conversion = st.selectbox('Selecciona la conversión:',
                                  ['Libras a kilogramos', 'Kilogramos a libras',
                                   'Onzas a gramos', 'Gramos a onzas'])
        valor = st.number_input('Introduce el valor:')
        if conversion == 'Libras a kilogramos':
            resultado = valor * 0.453592
        elif conversion == 'Kilogramos a libras':
            resultado = valor / 0.453592
        elif conversion == 'Onzas a gramos':
            resultado = valor * 28.3495
        elif conversion == 'Gramos a onzas':
            resultado = valor / 28.3495
        st.write(f'El resultado es: {resultado}')

    elif categoria == 'Volumen':
        conversion = st.selectbox('Selecciona la conversión:',
                                  ['Galones a litros', 'Litros a galones',
                                   'Pulgadas cúbicas a centímetros cúbicos',
                                   'Centímetros cúbicos a pulgadas cúbicas'])
        valor = st.number_input('Introduce el valor:')
        if conversion == 'Galones a litros':
            resultado = valor * 3.78541
        elif conversion == 'Litros a galones':
            resultado = valor / 3.78541
        elif conversion == 'Pulgadas cúbicas a centímetros cúbicos':
            resultado = valor * 16.387
        elif conversion == 'Centímetros cúbicos a pulgadas cúbicas':
            resultado = valor / 16.387
        st.write(f'El resultado es: {resultado}')

    elif categoria == 'Tiempo':
        conversion = st.selectbox('Selecciona la conversión:',
                                  ['Horas a minutos', 'Minutos a segundos',
                                   'Días a horas', 'Semanas a días'])
        valor = st.number_input('Introduce el valor:')
        if conversion == 'Horas a minutos':
            resultado = valor * 60
        elif conversion == 'Minutos a segundos':
            resultado = valor * 60
        elif conversion == 'Días a horas':
            resultado = valor * 24
        elif conversion == 'Semanas a días':
            resultado = valor * 7
        st.write(f'El resultado es: {resultado}')

    elif categoria == 'Velocidad':
        conversion = st.selectbox('Selecciona la conversión:',
                                  ['Millas por hora a kilómetros por hora',
                                   'Kilómetros por hora a metros por segundo',
                                   'Nudos a millas por hora', 'Metros por segundo a pies por segundo'])
        valor = st.number_input('Introduce el valor:')
        if conversion == 'Millas por hora a kilómetros por hora':
            resultado = valor * 1.60934
        elif conversion == 'Kilómetros por hora a metros por segundo':
            resultado = valor / 3.6
        elif conversion == 'Nudos a millas por hora':
            resultado = valor * 1.15078
        elif conversion == 'Metros por segundo a pies por segundo':
            resultado = valor * 3.28084
        st.write(f'El resultado es: {resultado}')

    elif categoria == 'Área':
        conversion = st.selectbox('Selecciona la conversión:',
                                  ['Metros cuadrados a pies cuadrados',
                                   'Pies cuadrados a metros cuadrados',
                                   'Kilómetros cuadrados a millas cuadradas',
                                   'Millas cuadradas a kilómetros cuadrados'])
        valor = st.number_input('Introduce el valor:')
        if conversion == 'Metros cuadrados a pies cuadrados':
            resultado = valor * 10.7639
        elif conversion == 'Pies cuadrados a metros cuadrados':
            resultado = valor / 10.7639
        elif conversion == 'Kilómetros cuadrados a millas cuadradas':
            resultado = valor * 0.386102
        elif conversion == 'Millas cuadradas a kilómetros cuadrados':
            resultado = valor / 0.386102
        st.write(f'El resultado es: {resultado}')

    elif categoria == 'Energía':
        conversion = st.selectbox('Selecciona la conversión:',
                                  ['Julios a calorías', 'Calorías a kilojulios',
                                   'Kilovatios-hora a megajulios', 'Megajulios a kilovatios-hora'])
        valor = st.number_input('Introduce el valor:')
        if conversion == 'Julios a calorías':
            resultado = valor * 0.239006
        elif conversion == 'Calorías a kilojulios':
            resultado = valor * 0.004184
        elif conversion == 'Kilovatios-hora a megajulios':
            resultado = valor * 3.6
        elif conversion == 'Megajulios a kilovatios-hora':
            resultado = valor / 3.6
        st.write(f'El resultado es: {resultado}')

    elif categoria == 'Presión':
        conversion = st.selectbox('Selecciona la conversión:',
                                  ['Pascales a atmósferas', 'Atmósferas a pascales',
                                   'Barras a libras por pulgada cuadrada',
                                   'Libras por pulgada cuadrada a bares'])
        valor = st.number_input('Introduce el valor:')
        if conversion == 'Pascales a atmósferas':
            resultado = valor / 101325
        elif conversion == 'Atmósferas a pascales':
            resultado = valor * 101325
        elif conversion == 'Barras a libras por pulgada cuadrada':
            resultado = valor * 14.5038
        elif conversion == 'Libras por pulgada cuadrada a bares':
            resultado = valor * 0.0689476
        st.write(f'El resultado es: {resultado}')

    elif categoria == 'Tamaño de Datos':
        conversion = st.selectbox('Selecciona la conversión:',
                                  ['Megabytes a gigabytes', 'Gigabytes a Terabytes',
                                   'Kilobytes a megabytes', 'Terabytes a petabytes'])
        valor = st.number_input('Introduce el valor:')
        if conversion == 'Megabytes a gigabytes':
            resultado = valor / 1024
        elif conversion == 'Gigabytes a Terabytes':
            resultado = valor / 1024
        elif conversion == 'Kilobytes a megabytes':
            resultado = valor / 1024
        elif conversion == 'Terabytes a petabytes':
            resultado = valor / 1024
        st.write(f'El resultado es: {resultado}')

# Llamar la función de conversión
convertir(categoria)