# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ufi6B5w94ClvNGe23tEoIIGoj2vp0K_e
"""

import streamlit as st
import random
import pandas as pd
import numpy as np
from scipy import stats

# Función para lanzar un dado
def lanzar_dado(n_lanzamientos):
    return [random.randint(1, 6) for _ in range(n_lanzamientos)]

# Título de la aplicación
st.title("Simulador de Lanzamiento de Dado")

# Mostrar los resultados de los lanzamientos
st.write('App por Juan Camilo Torres. Lanza un número de dados y '
         'calcula su media, mediana, moda, varianza y desviación estándar')

# Parámetro para el número de lanzamientos
n_lanzamientos = 20

# Lanzar el dado y guardar los resultados
resultados = lanzar_dado(n_lanzamientos)

# Mostrar los resultados de los lanzamientos
st.write(f"Resultados de los {n_lanzamientos} lanzamientos: {resultados}")

# Análisis estadístico
media = np.mean(resultados)
mediana = np.median(resultados)
moda_result = stats.mode(resultados)

# Aseguramos que tomamos solo el primer valor de la moda
moda = moda_result.mode[0]
varianza = np.var(resultados)
desviacion_estandar = np.std(resultados)

# Mostrar estadísticas
st.subheader("Análisis Estadístico")
st.write(f"Media: {media}")
st.write(f"Mediana: {mediana}")
st.write(f"Moda: {moda}")
st.write(f"Varianza: {varianza}")
st.write(f"Desviación Estándar: {desviacion_estandar}")

# Tabla de frecuencias
frecuencias = pd.DataFrame({
    'Número': [1, 2, 3, 4, 5, 6],
    'Frecuencia': [resultados.count(i) for i in range(1, 7)],
    'Porcentaje': [resultados.count(i) / n_lanzamientos * 100 for i in range(1, 7)]
})

# Mostrar tabla de frecuencias
st.subheader("Frecuencias de los Resultados")
st.write(frecuencias)