# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ufi6B5w94ClvNGe23tEoIIGoj2vp0K_e
"""

import streamlit as st
import numpy as np

# Simulación de lanzamientos de dado
lanzamientos = np.random.randint(1, 7, 20)

# Cálculos estadísticos
media = np.mean(lanzamientos)
mediana = np.median(lanzamientos)
moda = np.argmax(np.bincount(lanzamientos))  # Moda utilizando bincount
varianza = np.var(lanzamientos)
desviacion_estandar = np.std(lanzamientos)

# Análisis de frecuencias
frecuencias = np.bincount(lanzamientos)[1:]  # Ignorar el valor 0 en bincount
frequencies_table = np.array([np.arange(1, 7), frecuencias]).T

# Mostrar resultados
st.title("Simulación de Lanzamiento de Dados")
st.write('App por Juan Camilo Torres. Lanza 20 dados y '
         'calcula su media, mediana, moda, varianza y desviación estándar')
st.write("Se han realizado 20 lanzamientos del dado. Los resultados son los siguientes:")

# Mostrar los lanzamientos
st.write(lanzamientos)

# Mostrar análisis estadísticos
st.write(f"**Media**: {media}")
st.write(f"**Mediana**: {mediana}")
st.write(f"**Moda**: {moda}")
st.write(f"**Varianza**: {varianza}")
st.write(f"**Desviación Estándar**: {desviacion_estandar}")

# Mostrar tabla de frecuencias
st.write("**Tabla de Frecuencias**:")
st.write(frequencies_table, columns=["Número", "Frecuencia"])
