# -*- coding: utf-8 -*-
"""mi_primera_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14uS8HhY1nJykgarqC4gDQ9hIQpbGqoIT
"""

import streamlit as st

# Título de la app
st.title('Mi primera app')

# Autor de la app
st.write('Esta app fue elaborada por Juan Camilo Torres Arboleda.')

# Preguntar el nombre al usuario
nombre_usuario = st.text_input('¿Cuál es tu nombre?')

# Imprimir el mensaje de bienvenida
if nombre_usuario:
    st.write(f'{nombre_usuario}, te doy la bienvenida a mi primera app.')